default_agent: prechatAnalysisAgent
agents:
  prechatAnalysisAgent:
    name: prechatAnalysisAgent
    language: python
    node_version: null
    entrypoint: /Users/jaebin/AWS/repositories/prechat/packages/strands-agents/analysis-agent/agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: null
    aws:
      execution_role: arn:aws:iam::487498333664:role/AmazonBedrockAgentCoreSDKRuntime-ap-northeast-2-29a32885ca
      execution_role_auto_create: false
      account: '487498333664'
      region: ap-northeast-2
      ecr_repository: 487498333664.dkr.ecr.ap-northeast-2.amazonaws.com/bedrock-agentcore-prechatanalysisagent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: prechatAnalysisAgent-eKWZaFDty7
      agent_arn: arn:aws:bedrock-agentcore:ap-northeast-2:487498333664:runtime/prechatAnalysisAgent-eKWZaFDty7
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
